### ISSUE TITLE
"Directly inheriting from ActiveRecord::Migration is not supported." on install

### ISSUE THREAD

**Issue by hrdchz** [solidusio-contrib/solidus_trackers#21]
I had a confusing time getting this installed on Rails 5. It looks like the migrations are not properly set to work with `solidus_support`.

It looks like the issue was introduced here:

https://github.com/solidusio-contrib/solidus_trackers/commit/eecce5a2307e92929399acdd7ae82261be0a0766#diff-8261e5722470119bb36ac6ee74adc112R1

I originally thought this was the commit, more info here:

https://github.com/solidusio-contrib/solidus_trackers/commit/a5c86df730b00456a9f5077ecc1b9c645a8b61c1#comments

I'd do this as a PR but I'm still fairly green on Rails / Solidus. Its just "looks like" this is the issue to me.

**Comment by aldesantis** [comment]
@hrdchz sorry about that, I've opened a PR which addresses the issue!

**Comment by aldesantis** [comment]
Now fixed, thanks again. 😃
